---

- name: create loesche config dir
  file:
   path: /home/chaos/.config/loesche
   state: directory
   owner: "{{ user_name }}"
   group: "{{ user_group }}"

- name: copy loesche config file
  copy:
    src: loesche.conf
    dest: /home/chaos/.config/loesche
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

