---

- name: create mpv config dir
  file:
   path: /home/chaos/.config/mpv
   state: directory
   owner: "{{ user_name }}"
   group: "{{ user_group }}"

- name: copy mpv config file
  copy:
    src: mpv.conf
    dest: /home/chaos/.config/mpv
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

