---

- name: create mpv config dir
  file:
   path: /home/chaos/.config/mpv
   state: directory
   owner: chaos
   group: chaos

- name: copy mpv config file
  copy:
    src: mpv.conf
    dest: /home/chaos/.config/mpv
    owner: chaos
    group: chaos

