---
- name: isntall base packages
  pacman:
    name:
      - htop
      - fd
      - bat
      - zoxide
      - ripgrep
      - ripgrep-all
      - repgrep
      - cronie
      - python-passlib
      - vivid
      - apparmor
      - audit
      - python-notify2
      - python-psutil
      - udisks2
    state: present
