---
- name: add sudo conf for aur
  tags: always
  lineinfile:
    path: /etc/sudoers
    line: '{{user_name}} ALL=(ALL) NOPASSWD: /usr/bin/pacman'

- name: install AUR helper
  become: no
  aur:
    name: paru
    use: makepkg
    skip_installed: true
