---
- name: create aur_builder user
  become: yes
  block:
    - ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel
    - ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        state: present
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        mode: 0644
        validate: /usr/sbin/visudo -cf %s

- name: install AUR helper
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
