---
- name: create aur_builder user
  become: yes
  block:
    - ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel
    - ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        state: present
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        mode: 0644
        validate: /usr/sbin/visudo -cf %s

- name: add sudo conft for aur
  tags: always
  lineinfile:
    path: /etc/sudoers
    line: "chaos ALL=(ALL) NOPASSWD: /usr/bin/pacman"

- name: install AUR helper
  become: no
  aur:
    name: trizen
    use: makepkg
