- name: Add ansible-aur module as a a submodule
  git:
    repo: git@github.com:kewlfft/ansible-aur.git
    path: "/home/{{ user_name }}/DEV/ansible-desktop/plugins/modules/aur"
    submodule: yes
    recursive: yes
    force: yes
