- name: install base packages
  pacman:
    name:
      - fzf
      - htop
      - python-passlib
      - udisks2
    state: present

- name: install base packages (Rust CLI)
  pacman:
    name:
      - bat
      - bat-extras
      - eza
      - fd
      - ripgrep
      - ripgrep-all
      - repgrep
      - vivid
      - yazi
      - zoxide
    state: present

- name: install base packages (apparmor)
  pacman:
    name:
      - apparmor
      - audit
      - python-notify2
      - python-psutil
    state: present
